#!/bin/sh
#
# A pre-commit hook script to verify what is about to be committed.
# Called by "git commit" with no arguments. The hook exits with non-zero
# status after issuing an appropriate message if it wants to stop the commit.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

### Mandatory project checks

# ensure the snap package builds
echo "Building snap package..."
if ! snapcraft pack
then
    echo "The snap package failed to build. Please check the build log."
    exit 1
fi

# ensure code passes spread tests
echo "Running spread tests..."
if ! snapcraft test
then
    echo "Some tests are not passing. Please fix and check the test log."
    exit 1
fi

# find the generated snap package to lint
SNAP_FILE=$(find . -maxdepth 1 -name "*.snap" | head -n 1)
if [ -z "$SNAP_FILE" ]; then
    echo "No snap package found to lint."
    exit 1
fi

## Disable until https://github.com/canonical/snapcraft/issues/6332 is corrected
# ensure snap package passes snapcraft linter
#echo "Running linter on $SNAP_FILE..."
#if ! snapcraft lint "$SNAP_FILE"
#then
#    echo "There are some linter issues. See linter log for details."
#    exit 1
#fi

exit 0
