name: rustup
base: core24
version: '1.28.2'
summary: The Rust toolchain installer
description: |
    Rustup installs The Rust Programming Language from the official release
    channels, enabling you to easily switch between stable, beta, and nightly
    compilers and keep them updated. It makes cross-compiling simpler with
    binary builds of the standard library for common platforms.
    And it runs on all platforms Rust supports, including Windows.
grade: stable
confinement: classic

parts:
  rustup:
    plugin: rust
    rust-use-global-lto: 1
    rust-no-default-features: 1
    rust-features:
      - no-self-update
      - curl-backend
      - reqwest-native-tls
      - reqwest-rustls-tls
    source: https://github.com/rust-lang/rustup.git
    source-type: git
    source-tag: '1.28.2'
    build-packages:
      - pkg-config
      - libssl-dev
      - zlib1g-dev
      - cmake
      - clang
    build-environment:
      - RUSTFLAGS: >
          -Clink-arg=-Wl,-rpath=\$ORIGIN/lib:/snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
          -Clink-arg=-Wl,-dynamic-linker=$(find /snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR -name 'ld*.so.*' -print | head -n1)
    override-prime: |
        craftctl default
        mv -v "$CRAFT_PRIME"/bin/rustup-init "$CRAFT_PRIME"/bin/rustup
        # create symlinks to other tools
        _bins=(rustc cargo cargo-clippy cargo-fmt cargo-miri clippy-driver rust-gdb rust-lldb rls rust-analyzer rustdoc rustfmt)
        for b in "${_bins[@]}"; do
            ln -sv rustup "$CRAFT_PRIME"/bin/$b
        done

apps:
  rustup:
    command: bin/rustup
  cargo:
    command: bin/cargo
  rustc:
    command: bin/rustc
  cargo-clippy:
    command: bin/cargo-clippy
  cargo-fmt:
    command: bin/cargo-fmt
  cargo-miri:
    command: bin/cargo-miri
  clippy-driver:
    command: bin/clippy-driver
  rust-gdb:
    command: bin/rust-gdb
  rust-lldb:
    command: bin/rust-lldb
  rls:
    command: bin/rls
  rust-analyzer:
    command: bin/rust-analyzer
  rustdoc:
    command: bin/rustdoc
  rustfmt:
    command: bin/rustfmt
